### ISSUE TITLE
Typo в фінальному тексті 6 пункту

### ISSUE THREAD

**Issue by madsmile** [Yaroslav-F/trust#3]
Підсумовуючи результати:
За 0%, справедливий Імітатор перемагає! За 1% - 9%, поблажливий Добряк перемагає! За 10% - 49%: несправделивий, безпощадний Ша**з**рай перемагає. За 50%, ніхто не має шансу перемогти.

Ша**х**рай

![image](https://user-images.githubusercontent.com/3073619/69913481-0ce53880-1441-11ea-833d-02957369ccfa.png)

**Comment by Yaroslav-F** [comment]
Спасибі! Якщо знайдеться ще щось - дайте знати, будь ласка.
