### ISSUE TITLE
Шось сі поламало

### ISSUE THREAD

**Issue by danbst** [Yaroslav-F/trust#5]
https://yaroslav-f.github.io/trust/

Заходжу на сторінку, а там - порожньо. В консолі бачу:

![image](https://user-images.githubusercontent.com/743057/81835192-9ea5b580-954a-11ea-950e-d2323bf5567f.png)

Вогнелис 72.0.2

**Comment by mrRomanko** [comment]
Та нє, робе

**Comment by danbst** [comment]
ну як робе то добре
